- hosts: scripts-proxy
  serial: 1
  pre_tasks:
  - include_role:
      name: proxy-network
  - name: Install packages
    package:
      name:
        - open-vm-tools
      state: present
  - name: Disable Munin conntrack plugins
    copy:
      dest: /etc/munin/plugin-conf.d/
      src: files/conntrack
  roles:
    - role: rpm-repos
      tags: [always]
    - ansible-config-me
    - k5login
    - syslog-client
    - root-aliases
    - proxy-munin-node
    - nrpe
    - dnf-automatic
    - proxy-dns
    - proxy-haproxy
    - proxy-logrotate
  tasks:
    - package:
        name:
          - vim
          - emacs-nox
        state: present
  handlers:
    - name: reboot
      include_tasks: reboot.yml
      listen: network changed
    - name: setup
      setup:
      listen: network changed
